name: build

on:
  push:
    branches:
      - "**" # matches every branch
      - "!master" # excludes master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Check code out
        uses: actions/checkout@v1

      - name: Install JS dependencies and build
        run: yarn && yarn build
