name: build-and-test

on:
  push:
    branches:
      - "**" # matches every branch
      - "!master" # excludes master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          registry-url: https://registry.npmjs.org/

      - run: git config --global init.defaultBranch master

      - name: Check code out
        uses: actions/checkout@v2

      - name: Install JS dependencies
        run: yarn --frozen-lockfile

      - name: Build package
        run: yarn build --noEmit

      - name: Run tests
        run: yarn test --coverage && codecov
