name: publish-docs

on:
  push:
    branches:
      # - "master"
      - "docs"

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          registry-url: https://registry.npmjs.org/

      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1

      - name: Set up git
        run: |
          git config --global init.defaultBranch master
          git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install JS dependencies
        run: yarn --frozen-lockfile
      - name: Build and publish docs
        run: |
          yarn build:docs
          echo "footer { display: none }" >> docs/assets/css/main.css
          yarn publish:docs
