name: publish-docs

on:
  push:
    branches:
      # - "master"
      - "docs"

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          registry-url: https://registry.npmjs.org/
      - run: git config --global init.defaultBranch master
      - name: Check code out
        uses: actions/checkout@v2
      - name: Install JS dependencies
        run: yarn --frozen-lockfile
      - name: Build docs
        run: yarn build:docs
      - name: Commit files
        uses: EndBug/add-and-commit@v7
        with:
          add: "docs"
          message: "Update documentation"
