name: publish

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1

      - name: Set up git
        run: |
          git config --global init.defaultBranch master
          git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install JS dependencies, build and test
        run: |
          yarn --frozen-lockfile
          yarn build
          yarn test:coverage

      - name: Automated Version Bump
        uses: "phips28/gh-action-bump-version@v8.1.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Rebuild package and publish
        run: |
          yarn build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build and publish docs
        run: |
          yarn build:docs
          yarn publish:docs

      - name: Upload coverage
        uses: codecov/codecov-action@v3
