name: release

on:
  push:
    branches:
      - "**" # matches every branch
      - "!master" # excludes master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          registry-url: https://registry.npmjs.org/
      - run: git config --global init.defaultBranch master
      - name: Check code out
        uses: actions/checkout@v2
      - name: Install JS dependencies
        run: yarn --frozen-lockfile
      - name: Run tests
        run: yarn test --coverage
      - name: Build package
        run: |
          yarn build
          npm pack
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cruud-connector
          path: techrah-cruud-connector-*
          retention-days: 5
